language: rust
matrix:
  include:
  - os: linux
    rust: stable
  - os: linux
    rust: beta
  - os: linux
    rust: nightly
  - os: osx
    rust: stable
script:
- |
  cargo build --verbose &&
  cargo test  --verbose
